services:
  # Database
  db:
    image: mysql:5.7
    volumes: ['./data/:/var/lib/mysql']
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command:
      --explicit_defaults_for_timestamp
      --skip-ssl
      --pid-file=/var/lib/mysql/mysqld.pid
      --lower_case_table_names=1
    networks:
      - wpsite
    platform: linux/x86_64
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    volumes:
      - './apache-config.conf:/etc/apache2/conf-enabled/servername.conf'
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
    platform: linux/amd64
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    restart: "no"
    volumes: 
      - './www/:/var/www/html'
      - './apache-config.conf:/etc/apache2/conf-enabled/servername.conf'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: