version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ./wordpress/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "password"
                
  db:
    image:  mysql:5.7
    command: --default-authentication-plugin=mysql_native_password  
    restart: "no" 
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"

  phpmyadmin:
    depends_on:      
    - db    
    image: phpmyadmin/phpmyadmin    
    links:      
    - db    
    ports:      
    - "8080:80"   
    restart: always 
